### ISSUE TITLE
camelCase needs to change to PascalCase in documentation

### ISSUE THREAD

**Issue by onebitme** [OpenSimulationInterface/osi-documentation#16]
Here in the documentation:
https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/interfaceconventions.html#message-naming

you might want to reconsider to change camelCase to PascalCase for message naming part?
Maybe I know wrong..

**Comment by vkresch** [comment]
@onebitme good point! Thanks for reporting! Feel free to open a PR in the [OSI repo documentation](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/doc/interfaceconventions.rst) for that.

**Comment by onebitme** [comment]
@vkresch Good to hear that!, I've did it. 👍
