### ISSUE TITLE
Bug: Build System Pipeline

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/osi-documentation#2]
#### Describe the bug
The build pipeline sends a fail because it is executed twice. Once on travisci.com and once on travisci.org.

#### Describe how to reproduce the bug
1. Go to 'Code Tab'
2. Click on 'Branches'
3. Click on 'red cross'
4. Look at TravisCI status

#### Describe the expected behavior
Only one pipeline is active.

#### Show some screenshots

![grafik](https://user-images.githubusercontent.com/11943343/64765388-57db6800-d544-11e9-8d1f-ea0c109fc3d3.png)

#### Describe the OS you are using
 - OS: [Windows 10]
 - Browser: [Firefox]

#### Additional context
There is a new payment model for TravisCI which leads to a 'migration' to the new domain.

**Comment by vkresch** [comment]
Fixed by adding environmental variable `GH_REPO_TOKEN` also to travis-ci.com.
