### ISSUE TITLE
Issues, enhancement suggestion w.r.t OSI documentation.

### ISSUE THREAD

**Issue by MonaliBarai** [OpenSimulationInterface/osi-documentation#3]
**Suggestion:**
1. It will be good if description is given for each topic in the fist page itself rather than asking user to go to particular page for checking description.
e.g OSI Validator
We can describe what exactly is OSI Validator and then mention about 'Installation guide', 'Usage', 'How to write Rule' etc.

2. Link:  https://opensimulationinterface.github.io/osi-documentation/osi-validator/osivalidator.html#module-osivalidator.osi_id_manager
 
get_all_messages_by_id(message_id, message_t=None) and get_message_by_id(message_id, message_t=None)
Both the functions mentioned above looks same and arguments passed in it is also same.
Please check.

**Enhancement:** 
1. ‘Child message’ type is not very clear and can do with little bit more explanation.
Direct Link : https://opensimulationinterface.github.io/osi-documentation/osi-validator/writing-rules.html

2. Link: https://opensimulationinterface.github.io/osi-documentation/osi-validator/osivalidator.html#module-osivalidator.osi_rules
add_rule(rule) -> Explanation is not very clear.

3. Link: https://opensimulationinterface.github.io/osi-documentation/osi-validator/osivalidator-module.html
Instead of  "Can not be validated by HAND" please use "Can not be validated manually."

**Issues:**
1. Hyperlink is broken for page “KPIs documentation“. It opens following URL with error 404  “https://opensimulationinterface.github.io/osi-documentation/osi-validator/KPIs/index.html“ on page 
Direct Link : “ https://opensimulationinterface.github.io/osi-documentation/osi-validator/osivalidator-module.html“.

2. Link is broken in Rules section. Please check sentence “The available rule and their usage are explained here: rules”.
Direct Link: " https://opensimulationinterface.github.io/osi-documentation/osi-validator/writing-rules.html"

3.  Spell Check In Coordinate system and reference point : 
     "Open Simulation **Interace** uses DIN ISO 8855:2013-11 for coordinate systems and transformations between **coorinate** systems. "
Please change it to 'INTERFACE' and 'COORDINATE'.

4. Corrections:  Duplication of words are seen at couple of places which are mentioned below - 
  a. In the link "https://opensimulationinterface.github.io/osi-documentation/osi-validator/setup.html 
 ==>  “Python 3.6 with virtual **environment environment**”.
   b. In the link "https://opensimulationinterface.github.io/osi-documentation/osi-validator/osivalidator.html" ==> "Check if a protobuf **message message** have an attribute/field even if this is a repeated field."

5. Link: https://opensimulationinterface.github.io/osi-documentation/osi-validator/osivalidator.html
"has_field(field_name)"
Check if a protobuf message **message** have an attribute/field even if this is a repeated field.
'message' is repeated.

6. Link : https://opensimulationinterface.github.io/osi-documentation/osi-validator/osivalidator.html#module-osivalidator.osi_scenario
In sentence "Module that contain OSIDataContainer class to handle and **manager** OSI scenarios.", replace 'manager' with 'manage'.

**Comment by jdsika** [comment]
@MonaliBarai you have to fill the template and update the headline here :)

**Comment by MonaliBarai** [comment]
> @MonaliBarai you have to fill the template and update the headline here :)

Done :-)

**Comment by jdsika** [comment]
@MonaliBarai can you please verify if your issues are addressed by the current PR #4

**Comment by vkresch** [comment]
@MonaliBarai the duplication for message [here](https://opensimulationinterface.github.io/osi-documentation/osi-validator/osivalidator.html#osivalidator.linked_proto_field.LinkedProtoField.has_field) is still there because it's a parsing from the osi-validator comments but will be corrected with the next commit to osi-validator.

**Comment by MonaliBarai** [comment]
Added few more issues, suggestions and enhancement.
1. Issue #5
2. Issue #6
3. Suggestion #2
4. Enhancement #2
5. Enhancement #3

**Comment by vkresch** [comment]
For now closing this issue. Further proof reading and improvement suggestion can be done in another issue.
