### ISSUE TITLE
Add contact information

### ISSUE THREAD

**Issue by max-rosin** [OpenSimulationInterface/osi-documentation#39]
Check whether and how to add contact information to the docs. This should be done in a way so that it applies to all OSI documents.
 
>@stefancyliax: [The following topic from the existing documentation](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/description.html#compatibility) holds the content that was originally intended to go into here. The original topic defines the terms "faithful", "forward compatibility" and "backward compatibility". I did not see these terms being used in the documentation. Do we need these definitions? If not, I would opt for removing the topic altogether
>
>On a second note, do we need a dedicated "contact" topic? Or should the contact information be part of the page layout, for example, the footer (as far as I can see, it isn't today)

_Originally posted by @max-rosin in https://github.com/OpenSimulationInterface/open-simulation-interface/pull/549#r681596121_

**Comment by stefancyliax** [comment]
Became not relevant. Contact to OSI should happen through issues in the repository.
