### ISSUE TITLE
Add doxygen reference documentation to sphinx

### ISSUE THREAD

**Issue by vkresch** [OpenSimulationInterface/osi-documentation#5]
#### Describe the feature
Currently we have two places for the documentation:
1) [doxygen OSI reference](https://opensimulationinterface.github.io/open-simulation-interface/)
2) [sphinx documentation](https://opensimulationinterface.github.io/osi-documentation/)

It would be beneficial if we could move the doxygen documentation into sphinx so that we only have one place for everything OSI related. The search via keywords would be much more effective since it would look through the **whole** documentation and won't miss out on some information. Sphinx also supports math latex output which would the math formulas make much more beautiful and readable and so on.

#### Describe the solution you would like
Since sphinx currently doesn't support direct comment parsing from `*.proto` files we can use the library [breathe](https://breathe.readthedocs.io/en/latest/) to parse the current `doxygen` documentation through xml which then can be parsed by sphinx. 

#### Describe alternatives you have considered
Alternative would be since doxygen and sphinx documentation are both html output formats to include manually the html doxygen into sphinx. Another alternative would be to keep it seperate but provided just simple links to doxygen in sphinx.

Also instead of using `breathe` there are libraries like:

- [doxyrest](https://github.com/vovkos/doxyrest)
- [Gasp](https://github.com/troelsfr/Gasp)
- [Robin](https://bitbucket.org/reima/robin/issues?status=new&status=open)
- [sphinxcontrib-autodoc_doxygen](https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen)

which also create a bridge between doxygen and sphinx.

**Comment by vkresch** [comment]
[Here](https://vkresch.github.io/osi-documentation/osi/reference.html) you can see the first prototype.
Current Pros:
+ general index search is for doxygen reference and sphinx pages possible
+ math equation look good 

Current Cons:
- no UML/Graph with relations between types of fields (maybe needs to be added manually or through hacking)
- HTML Tables (like in [this message](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1TrafficSign_1_1MainSign_1_1Classification.html)) in the comments are not supported (maybe we can get rid of them or use them in a more sphinx way)
- currently there is only a alphabetical sorting of messages and you can't really recognize nested messages (this is solveable by creating manually subtopics in sphinx)

**Comment by jdsika** [comment]
They definitly have some issues ;-)
![grafik](https://user-images.githubusercontent.com/11943343/65706189-32914280-e08a-11e9-80f3-32e4b01fcff8.png)

- Relation diagrams are somehow important
- If we have a proper solution we can rewrite the HTML tables. They are looking very good in doxygen but do not look pretty in the .proto files.
- The class list of doxygen is also somehow nice...

Good prototype and research! I think it is worth investigating more - maybe write some feeback for the breath project.and show them the results. maybe they can help?

**Comment by vkresch** [comment]
@jdsika I restuctred the sphinx documentation in a new way [here](https://vkresch.github.io/osi-documentation/api/library_root.html) with the library [exhale](https://exhale.readthedocs.io/en/latest/). The same cons as mentioned above apply but it is better structered. It has:

- Class Hierarchy
- File Hierarchy
- Library API with a tree view

for now I will use this for the official documentation and with a warning that it's a work in progress.

**Comment by jdsika** [comment]
Looks good! Write a small abstract above mentioning the "Work in Progress" and the Link to the separate Doxygen. Tell the user that the intention is a Single Document.

**Comment by jdsika** [comment]
I consider this "solved" and the explicit improvements can be done in separate issues.
