### ISSUE TITLE
Update documentation with more explicit statement for FMI 3.0

### ISSUE THREAD

**Issue by PhRosenberger** [OpenSimulationInterface/osi-documentation#65]
As FMI 3.0 is [available since a couple of months](https://fmi-standard.org/news/2022-05-10-fmi-3.0-release/), we should update the documentation and state something on the possibilities to use it.

However, the current implementation with the shared memory pointers is as efficient as it can get, even with the new availability for binary data transfer in FMI 3.0. So, I would propose only a change to the documentation and to spend some words on that.

**Comment by PhRosenberger** [comment]
I would propose to at least update https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/blob/master/doc/spec/binary_variables.adoc

**Comment by PhRosenberger** [comment]
@pmai do you see other files to update, as well?

**Comment by PhRosenberger** [comment]
@pmai and @thomassedlmayer please propose a statement on FMI 3.0 in https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/blob/master/doc/spec/binary_variables.adoc.

I do not expect this to be a major issue as it was discussed in the CCB today. I would say we should monitor this issue.

If possible, it would be great if you could already prepare something for OSi 3.6 to support FMI3.0.

**Comment by pmai** [comment]
Closed by OpenSimulationInterface/osi-sensor-model-packaging#109.
